packages:
  - 'playground'
  - 'client'
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  protobufjs: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@nuxt/kit'
  - nuxt
  - '@nuxt/schema'
  - '@nuxt/nitro-server@4.5.0 || 4.5.1'
  - '@nuxt/vite-builder@4.5.0 || 4.5.1'
  - '@nuxt/test-utils@4.1.0'
